exercises = [
    {
        'name': 'Arch Rock',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Back Squat',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': 'lb',   
    },
    {
        'name': 'Bench Press',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': 'lb',   
    },
    {
        'name': 'Box Jump',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Burpee',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Clean',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': 'lb',   
    },
    {
        'name': 'Clean and Jerk',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': 'lb',   
    },
    {
        'name': 'Chest to Bar',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Deadlift',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': 'lb',   
    },
    {
        'name': 'Double Unders',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Front Squat',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': 'lb',   
    },
    {
        'name': 'Hollow',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Hollow Rock',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Hand Stand Push-Up',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Knees to Elbows',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Muscle Up',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Over Head Squat',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': 'lb',   
    },
    {
        'name': 'Pistol squat',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Push Press',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': 'lb',   
    },
    {
        'name': 'Push Jerk',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': 'lb',   
    },
    {
        'name': 'Pull Up',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Push Up',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Ring Dips',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Rope Climb',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Sumo Deadlift',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': 'lb',   
    },
    {
        'name': 'Sumo Deadlift High Pull',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': 'lb',   
    },
    {
        'name': 'Shoulder Press',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': 'lb',   
    },
    {
        'name': 'Snatch',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': 'lb',   
    },
    {
        'name': 'Split Jerk',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': 'lb',   
    },
    {
        'name': 'Squat',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Sit Ups',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Single Unders',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Superman',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Toes to Bar',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'V-ups',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': None,   
    },
    {
        'name': 'Wall-Ball Shots',
        'reps': None,
        'start': None,
        'end': None,
        'weight': None,
        'unit': 'lbs',   
    },








]