types = [
    {
        'title': 'Every Minute on a Minute',
        'description': 'mortal cardio',
        'name': None,
        'type': 'emom',
        'time': None,
        'rest': 0,
        'rounds': None,
    },
    {
        'title': 'As Many Rounds As Possible',
        'description': 'mortal cardio',
        'name': None,
        'type': 'amrap',
        'time': None,
        'rest': 0,
        'rounds': None,
    },
    {
        'title': 'Rounds For Time',
        'description': 'mortal cardio',
        'name': None,
        'type': 'rft',
        'time': None,
        'rest': 0,
        'rounds': None,
    },
    {
        'title': 'Chipper',
        'description': 'mortal cardio',
        'name': None,
        'type': 'chipper',
        'time': None,
        'rest': 0,
        'rounds': None,
    },
    {
        'title': 'Ladder',
        'description': 'mortal cardio',
        'name': None,
        'type': 'ladder',
        'time': None,
        'rest': 0,
        'rounds': None,
    },
    {
        'title': 'Tabata',
        'description': 'mortal cardio',
        'name': None,
        'type': 'tabata',
        'time': 240,
        'rest': 0,
        'rounds': None,
    },
    {
        'title': 'Buy-in or Cash Out',
        'description': 'mortal cardio',
        'name': None,
        'type': 'buy_in_cash_out',
        'time': None,
        'rest': 0,
        'rounds': None,
    }
]
